quartz:
  enabled: true
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/architect
    username: root
    password: 123
    tomcat:
      initialSize: 20
      maxActive: 100
      maxIdle: 100
      minIdle: 20
      maxWait: 10000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false