server:
  port: 8888

spring:
  redis:
    database: 0
    sentinel:    #哨兵模式
      master: mymaster #主服务器所在集群名称
      nodes: 127.0.0.1:26379  #哨兵节点
    lettuce:
      pool:  #Redis连接池配置
        max-idle: 50    #最大空闲连接数
        min-idle: 10    #最小空闲连接数
        max-active: 100 #最大连接数

