server:
  port: 8888

spring:
  redis:
    database: 0
    lettuce:
      pool: #Redis连接池配置
        max-idle: 50    #最大空闲连接数
        min-idle: 10    #最小空闲连接数
        max-active: 100 #最大连接数
    host: 127.0.0.1
    port: 6379

